(SERVER-548) Use text/plain for file_bucket_file GET responses
Without this patch the file_bucket_file get responses (not requests) to
Puppet 3 clients have Content-Type: application/octet-stream set, which
the Puppet 3 agent handles by blowing up with:

    Error: Could not run: Could not intern from application/octet-stream:
      No format match the given format name or mime-type
      (application/octet-stream)

This patch addresses the problem by implementing a ring middleware
specifically for file_bucket_file GET requests.  This middleware
function sets the content-type header to text/plain, which is handled by
Puppet 3.